import { Box, Grid, Stack, ThemeProvider, Typography } from "@mui/material";
import Head from "next/head";
import Header from "../components/Header";
import ServicesCard from "../components/ServicesCard";
import theme from "../styles/theme";

export default function Home() {
  const ServicesList = [
    {
      title: "Lizard",
      des: `Lizards are a widespread group of squamate reptiles, with over 6,000
  species, ranging across all continents except Antarctica`,
    },
    {
      title: "Lizard",
      des: `Lizards are a widespread group of squamate reptiles, with over 6,000
  species, ranging across all continents except Antarctica`,
    },
    {
      title: "Lizard",
      des: `Lizards are a widespread group of squamate reptiles, with over 6,000
  species, ranging across all continents except Antarctica`,
    },
    {
      title: "Lizard",
      des: `Lizards are a widespread group of squamate reptiles, with over 6,000
  species, ranging across all continents except Antarctica`,
    },
    {
      title: "Kabsaa",
      des: ` This impressive paella is a perfect party dish and a fun meal to cook
  together with your guests. Add 1 cup of frozen peas along with the mussels,
  if you like.`,
    },
    {
      title: "Kabsaa",
      des: ` This impressive paella is a perfect party dish and a fun meal to cook
  together with your guests. Add 1 cup of frozen peas along with the mussels,
  if you like.`,
    },
    {
      title: "Kabsaa",
      des: ` This impressive paella is a perfect party dish and a fun meal to cook
  together with your guests. Add 1 cup of frozen peas along with the mussels,
  if you like.`,
    },
  ];
  return (
    <>
      <ThemeProvider theme={theme}>
        <Head>
          <title>خدماتي</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <Stack>
          <Box
            p={10}
            justifyContent={"center"}
            bgcolor={(theme) => theme.palette.primary.main}
          >
            <Typography textAlign={"center"} variant="h3">
              انجاز الخدمات الالكترونية
            </Typography>
          </Box>
          <Grid
            container
            justifyContent={"space-evenly"}
            bgcolor={"whitesmoke"}
            spacing={1}
           
          >
            {ServicesList.map((i) => (
              <Grid item >
                <ServicesCard title={i.title} des={i.des}></ServicesCard>
              </Grid>
            ))}
          </Grid>
        </Stack>
      </ThemeProvider>
    </>
  );
}
